# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
        readinessProbe:                     # 👈 Endpoint için önemli
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:                      # 👈 Sağlık durumu için önemli
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
