global:
  hosts:
    domain: 192.168.56.110.nip.io
  edition: ce

# Reduce the number of replicas for a minimal setup
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

# Disable services that are not essential for a minimal setup
gitlab-runner:
  install: false

certmanager:
  install: false

nginx-ingress:
  enabled: true

prometheus:
  install: false

grafana:
  install: false

# Use smaller persistent volume claims
gitlab:
  gitaly:
    persistence:
      size: 10Gi
  postgresql:
    persistence:
      size: 10Gi
  redis:
    persistence:
      size: 5Gi
